/*
 * CartesianCoordinate
 * 
 * Copyright (c) 2017 by xabuloes, http://github.com/xabuloes
 *
 * This file is part of the Wahlzeit photo rating application.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */

package org.wahlzeit.model;

/**
 * A coordinate represented by the Cartesian system with values x, y and z.
 * 
 * @author xabuloes
 *
 */
public class CartesianCoordinate extends AbstractCoordinate {

	private double x;

	private double y;

	private double z;

	/**
	 * TODO
	 * 
	 * @param x
	 * @param y
	 * @param z
	 */
	public CartesianCoordinate(double x, double y, double z) {
		super();

		this.setX(x);
		this.setY(y);
		this.setZ(z);
	}

	/**
	 * TODO
	 * 
	 * @return X value of coordinate.
	 */
	public double getX() {
		// No assertions, since this is only a getter
		return x;
	}

	/**
	 * TODO
	 * 
	 * @param x
	 *            New X value of coordinate.
	 */
	public void setX(double x) {
		this.assertClassInvariants();
		
		this.x = x;
		
		this.assertClassInvariants();
	}

	/**
	 * TODO
	 * 
	 * @return Y value of coordinate.
	 */
	public double getY() {
		// No assertions, since this is only a getter
		return y;
	}

	/**
	 * TODO
	 * 
	 * @param y
	 *            New Y value of coordinate.
	 */
	public void setY(double y) {
		this.assertClassInvariants();
		
		this.y = y;
		
		this.assertClassInvariants();
	}

	/**
	 * TODO
	 * 
	 * @return Z value of coordinate.
	 */
	public double getZ() {
		// No assertions, since this is only a getter
		return z;
	}

	/**
	 * TODO
	 * 
	 * @param z
	 *            New Z value of coordinate.
	 */
	public void setZ(double z) {
		this.assertClassInvariants();
	
		this.z = z;
		
		this.assertClassInvariants();
	}

	/**
	 * This method is auto-generated by Eclipse. hashCode() has to be implemented
	 * when equals is overridden
	 * 
	 * @return hashCode
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(x);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(y);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(z);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	/**
	 * Return Cartesian coordinate value (trivial in this case; method exists to
	 * have interchangeable coordinate representations)
	 * 
	 * @return The coordinate object's instance
	 */
	public CartesianCoordinate asCartesianCoordinate() {
		// No assertions, since this is only a getter
		return this;
	}

	/**
	 * Return a new coordinate object, representing the Cartesian coordinate in a
	 * spheric representation
	 * 
	 * @return Converted coordinate values as a new object
	 */
	public SphericCoordinate asSphericCoordinate() {
		this.assertClassInvariants();
		
		final double latitude = Math.atan(Math.sqrt(this.getX() * this.getX() + this.getY() * this.getY()) / this.getZ());
		final double longitude = Math.atan(this.getY() / this.getX());
		final double radius = Math.sqrt(this.getX() * this.getX() + this.getY() * this.getY() + this.getZ() * this.getZ());

		final SphericCoordinate sphericCoordinate = new SphericCoordinate(latitude, longitude, radius);
		
		this.assertClassInvariants();
		
		return sphericCoordinate;
	}

	/**
	 * Calculates the distance between the associated coordinate object and the
	 * given coordinate object.
	 * 
	 * @param coordinateB
	 *            Coordinate to which distance should be calculated; If not
	 *            Cartesian, it is converted to a Cartesian coordinate
	 * @return Distance calculated based on the Cartesian system
	 */
	@Override
	public double doGetCartesianDistance(Coordinate coordinateB) {
		this.assertClassInvariants();
		this.assertValueIsNotNull(coordinateB);

		CartesianCoordinate asCartesianCoordinate = coordinateB.asCartesianCoordinate();

		final double dx = Math.abs(this.getX() - asCartesianCoordinate.getX());
		final double dy = Math.abs(this.getY() - asCartesianCoordinate.getY());
		final double dz = Math.abs(this.getZ() - asCartesianCoordinate.getZ());

		final double cartesianDistance = Math.sqrt(dx * dx + dy * dy + dz * dz);
		
		this.assertDoubleValueIsGreaterOrEqualThanZero(cartesianDistance);
		this.assertClassInvariants();
		
		return cartesianDistance;
	}

	/**
	 * Delegates calculation of spheric distance to SphericCoordinate, since this is
	 * a Cartesian coordinate.
	 * 
	 * @param coordinateB
	 *            Coordinate to which distance should be calculated
	 * @return Distance calculated based on the Spheric system
	 */
	@Override
	public double doGetSphericDistance(Coordinate coordinateB) {
		this.assertClassInvariants();
		this.assertValueIsNotNull(coordinateB);
		
		final double sphericDistance = this.asSphericCoordinate().getSphericDistance(coordinateB);
		
		this.assertDoubleValueIsGreaterOrEqualThanZero(sphericDistance);
		this.assertClassInvariants();
		
		return sphericDistance;
	}

	/**
	 * Since this is an instance of CartesianCoordinate, we delegate this call to
	 * the Cartesian distance calculation.
	 * 
	 * @param coordinateB
	 *            Coordinate to which distance should be calculated
	 * @return Distance calculated
	 */
	@Override
	protected double doGetDistance(Coordinate coordinateB) {
		this.assertClassInvariants();
		
		final double distance = this.doGetCartesianDistance(coordinateB);
		
		this.assertClassInvariants();
		
		return distance;
	}
	
	/**
	 * TODO 
	 */
	@Override
	protected void assertClassInvariants() {
		
		// Nothing to assert here
		
		super.assertClassInvariants();
	}

}
