/*
 * Coordinate
 * 
 * Copyright (c) 2017 by xabuloes, http://github.com/xabuloes
 *
 * This file is part of the Wahlzeit photo rating application.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */

package org.wahlzeit.model;

/**
 * A Coordinate represents a coordinate in a 3D Cartesian coordinate system.
 * 
 * @author xabuloes
 *
 */
public class Coordinate {

	// Coordinate values
	private double x;
	private double y;
	private double z;

	public Coordinate(double x, double y, double z) {
		this.x = x;
		this.y = y;
		this.z = z;
	}

	/**
	 * 
	 * @return	X value of coordinate.
	 */
	public double getX() {
		return x;
	}

	/**
	 * 
	 * @param x	New X value of coordinate.
	 */
	public void setX(double x) {
		this.x = x;
	}

	/**
	 * 
	 * @return	Y value of coordinate.
	 */
	public double getY() {
		return y;
	}

	/**
	 * 
	 * @param y	New Y value of coordinate.
	 */
	public void setY(double y) {
		this.y = y;
	}

	
	/**
	 * 
	 * @return Z value of coordinate.
	 */
	public double getZ() {
		return z;
	}

	/**
	 * 
	 * @param z	New Z value of coordinate.
	 */
	public void setZ(double z) {
		this.z = z;
	}

	/**
	 * Calculates the distance between the associated coordinate object and the
	 * given coordinate object.
	 * 
	 * @param coordinateB
	 *            Coordinate to which distance should be calculated
	 * @return calculated distance between the two coordinates in the coordinate
	 *         system
	 * @throws IllegalArgumentException
	 *             When input coordinate is null
	 */
	public double getDistance(Coordinate coordinateB) throws IllegalArgumentException {

		if (coordinateB == null) {
			throw new IllegalArgumentException("null value was given to calculate distance between to coordinates");
		}

		final double dx = Math.abs(this.x - coordinateB.x);
		final double dy = Math.abs(this.y - coordinateB.y);
		final double dz = Math.abs(this.z - coordinateB.z);

		return Math.sqrt(dx * dx + dy * dy + dz * dz);
	}

	/**
	 * Compares the x, y and z values of the associated coordinate object with the
	 * given coordinate object.
	 * 
	 * @param toCompare
	 *            Coordinate object that should be compared to associated Coordinate
	 *            object
	 * @return true if x,y and z are equal in both coordinates, false if at least
	 *         one is not equal.
	 */
	public boolean isEqual(Coordinate toCompare) {
		if (toCompare == null) {
			return false;
		}

		return (this.getX() == toCompare.getX()) && (this.getY() == toCompare.getY())
				&& (this.getZ() == toCompare.getZ());
	}

	/**
	 * This method is auto-generated by Eclipse. hashCode() has to be implemented
	 * when equals is overridden.
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(x);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(y);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(z);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	/**
	 * 
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj.getClass() != Coordinate.class) {
			return false;
		}

		return this.isEqual((Coordinate) obj);
	}

}
