/*
 * SphericCoordinate
 * 
 * Copyright (c) 2017 by xabuloes, http://github.com/xabuloes
 *
 * This file is part of the Wahlzeit photo rating application.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */

package org.wahlzeit.model;

/**
 * A coordinate representing a position defined by spheric values (radius, azimuth and polar angle).
 */
public class SphericCoordinate extends AbstractCoordinate {

	/**
	 * Latitude (polar angle in radian measure)
	 */
	private double latitude;

	/**
	 * Longitude (azimuth angle in radian measure)
	 */
	private double longitude;

	/**
	 * Radius
	 */
	private double radius;

	/**
	 *
	 * @param latitude
	 *            in radian measure
	 * @param longitude
	 *            in radian measure
	 * @param radius
	 *            Radius
	 */
	public SphericCoordinate(double latitude, double longitude, double radius) {
		super();

		this.setLatitude(latitude);
		this.setLongitude(longitude);
		this.setRadius(radius);
	}

	/**
	 * Get latitude value.
	 * 
	 * @return
	 */
	public double getLatitude() {
		// No assertions, since this is only a getter
		return latitude;
	}

	/**
	 * Set latitude in radian measure.
	 * 
	 * @param latitude
	 *            Radian value in the range [0;PI*2[
	 */
	public void setLatitude(double latitude) {

		this.assertDoubleIsFiniteNumber(latitude);
		this.assertValueIsInRadianRange(latitude);
		
		this.latitude = latitude;
		
		this.assertClassInvariants();
	}

	/**
	 * Get longitude value.
	 * 
	 * @return
	 */
	public double getLongitude() {
		// No assertions, since this is only a getter
		return longitude;
	}

	/**
	 * Set longitude in radian measure.
	 * 
	 * @param longitude
	 *            Radian value in the range [0;PI*2[
	 */
	public void setLongitude(double longitude) {
		
		this.assertDoubleIsFiniteNumber(longitude);
		this.assertValueIsInRadianRange(longitude);

		this.longitude = longitude;
		
		this.assertClassInvariants();
	}

	/**
	 * Get radius value.
	 * 
	 * @return
	 */
	public double getRadius() {
		// No assertions, since this is only a getter
		return radius;
	}

	/**
	 * Set radius to given value.
	 * 
	 * @param radius
	 */
	public void setRadius(double radius) {
		
		this.assertDoubleIsFiniteNumber(radius);
		this.assertDoubleValueIsGreaterOrEqualThanZero(radius);

		this.radius = radius;
		
		this.assertClassInvariants();
	}

	/**
	 * {@inheritDoc}
	 */
	public CartesianCoordinate asCartesianCoordinate() {

		final double x = this.getRadius() * Math.sin(this.getLatitude()) * Math.cos(this.getLongitude());
		final double y = this.getRadius() * Math.sin(this.getLatitude()) * Math.sin(this.getLongitude());
		final double z = this.getRadius() * Math.cos(this.getLatitude());

		this.assertClassInvariants();
		
		return new CartesianCoordinate(x, y, z);
	}

	/**
	 * {@inheritDoc}
	 */
	public SphericCoordinate asSphericCoordinate() {
		return this;
	}

	/**
	 * This method is auto-generated by Eclipse. hashCode() has to be implemented
	 * when equals is overridden.
	 * 
	 * @return hashCode
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(latitude);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(longitude);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(radius);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected double doGetDistance(Coordinate coordinateB) throws IllegalArgumentException {
		return this.doGetSphericDistance(coordinateB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected double doGetCartesianDistance(Coordinate coordinateB) {
		return this.asCartesianCoordinate().getCartesianDistance(coordinateB);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected double doGetSphericDistance(Coordinate coordinateB) {
		// TODO: This calculation is wrong, fix it!
		return this.asCartesianCoordinate().getCartesianDistance(coordinateB);
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected void assertClassInvariants() {
		
		this.assertDoubleIsFiniteNumber(this.longitude);
		this.assertValueIsInRadianRange(this.longitude);
		
		this.assertDoubleIsFiniteNumber(this.latitude);
		this.assertValueIsInRadianRange(this.latitude);
		
		this.assertDoubleIsFiniteNumber(this.radius);
		this.assertDoubleValueIsGreaterOrEqualThanZero(this.radius);
		
		super.assertClassInvariants();
	}
	
	/**
	 * Assert that valueShouldBeInRadianRange is within valid radian range [0;2*PI[.
	 * Method is protected to allow usage in further sub classes.
	 * 
	 * @param valueShouldBeInRadianRange
	 * @return
	 */
	protected final void assertValueIsInRadianRange(double valueShouldBeInRadianRange) {
		if(valueShouldBeInRadianRange < 0 || valueShouldBeInRadianRange >= Math.PI * 2) {
			throw new CoordinateAssertionError("Value " + valueShouldBeInRadianRange + " is not a valid radian value ( range: [0;PI*2[ ).");
		}
	}

}
